# -*- mode: ruby -*-
# vi: set ft=ruby :

#define server details
	varnish_servers = [
		{
			:hostname => 'cache1',
			:box => 'varnish/ubuntu-14.04-amd64',
			:box_url => 'https://images.varnish-software.com/vagrant/ubuntu-14.04-amd64.json',
			:versionscript => 'scripts/varnish4.sh',
			:startscript => 'scripts/cache1.sh',
			:varnishport => '6081',
			:varnishHostport => '16081',
			:agentPort => '16085',
			:internalIP => "192.168.50.101"
		},
		{
			:hostname => 'cache2',
			:box => 'varnish/ubuntu-14.04-amd64',
			:box_url => 'https://images.varnish-software.com/vagrant/ubuntu-14.04-amd64.json',
			:versionscript => 'scripts/varnish4.sh',
			:startscript => 'scripts/cache2.sh',
			:varnishport => '6081',
			:varnishHostport => '26081',
			:agentPort => '26085',
			:internalIP => "192.168.50.102"
		},
		{
			:hostname => 'cache3',
			:box => 'varnish/ubuntu-14.04-amd64',
			:box_url => 'https://images.varnish-software.com/vagrant/ubuntu-14.04-amd64.json',
			:versionscript => 'scripts/varnish41.sh',
			:startscript => 'scripts/cache3.sh',
			:varnishport => '6081',
			:varnishHostport => '36081',
			:agentPort => '36085',
			:internalIP => "192.168.50.103"
		},
		{
			:hostname => 'cache4',
			:box => 'varnish/ubuntu-14.04-amd64',
			:box_url => 'https://images.varnish-software.com/vagrant/ubuntu-14.04-amd64.json',
			:versionscript => 'scripts/varnish41.sh',
			:startscript => 'scripts/cache4.sh',
			:varnishport => '6081',
			:varnishHostport => '46081',
			:agentPort => '46085',
			:internalIP => "192.168.50.104"
		},
		{
			:hostname => 'cache5',
			:box => 'varnish/ubuntu-14.04-amd64',
			:box_url => 'https://images.varnish-software.com/vagrant/ubuntu-14.04-amd64.json',
			:versionscript => 'scripts/varnish3.sh',
			:startscript => 'scripts/cache5.sh',
			:varnishport => '6081',
			:varnishHostport => '44081',
			:agentPort => '44085',
			:internalIP => "192.168.50.105"
		},
	]

Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |v|
	  v.customize [ "guestproperty", "set", :id, "--timesync-threshold", 10000 ]
	end
	varnish_servers.each do |cache|
		config.vm.define cache[:hostname] do |cacheconfig|
			cacheconfig.vm.box = cache[:box]
			cacheconfig.vm.box_url = cache[:box_url]
			cacheconfig.vm.hostname = cache[:hostname]
			cacheconfig.vm.provision :shell, path: cache[:versionscript]
			cacheconfig.vm.provision :shell, path: cache[:startscript]
			cacheconfig.vm.network "private_network", ip: cache[:internalIP]
			cacheconfig.vm.network :forwarded_port, guest: cache[:varnishport], host: cache[:varnishHostport]
			cacheconfig.vm.network :forwarded_port, guest: cache[:agentPort], host: cache[:agentPort]
		end
	end
end
